### ISSUE TITLE
TYPO3 version dependency update to 10.4 possible?

### ISSUE THREAD

**Issue by rowild** [Thejuse/cookiebanner#4]
Hi!

Currently, the TYPo3 version dependency is 10.3.99. Any chance to increase that? So far I didn't see any problems with the ext.

**Comment by Thejuse** [comment]
Hej rowild,

I‘ll check that today and will publish the update asap.

Should be today or tomorrow

**Comment by rowild** [comment]
@Thejuse Thank you very much, Julian! Take your time!

**Comment by Thejuse** [comment]
Hey @rowild 
The Release 1.4.3 is now uploaded in the TYPO3 TER.

It should be available to download in a few minutes.
